[project]
name = "langchaintutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.7.13",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
]

[project.scripts]
langchaintutorial = "langchaintutorial:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
